import { expect, test, type Page } from '@playwright/test'

const elements = (page: Page) => page.getByTestId('drawing-elements').locator(':scope > *')

async function draw(page: Page, from: [number, number], to: [number, number]) {
  await page.mouse.move(...from)
  await page.mouse.down()
  await page.mouse.move(...to, { steps: 8 })
  await page.mouse.up()
}

test('pen, colors, widths, shapes, erasing, and clear confirmation', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.screenshot({ path: testInfo.outputPath('desktop.png') })
  await page.getByRole('radio', { name: 'Blue', exact: true }).click()
  await page.getByRole('radio', { name: 'Bold stroke' }).click()
  await draw(page, [350, 300], [480, 390])
  await expect(elements(page)).toHaveCount(1)
  await expect(elements(page).first()).toHaveAttribute('stroke', '#4878c8')
  await expect(elements(page).first()).toHaveAttribute('stroke-width', '6')
  await page.mouse.click(550, 300)
  await expect(elements(page)).toHaveCount(2)
  await expect(elements(page).nth(1)).toHaveAttribute('r', '3')

  await page.getByRole('button', { name: 'Rectangle (R)', exact: true }).click()
  await page.keyboard.down('Shift')
  await draw(page, [600, 300], [720, 360])
  await page.keyboard.up('Shift')
  await expect(elements(page).nth(2)).toHaveAttribute('width', '120')
  await expect(elements(page).nth(2)).toHaveAttribute('height', '120')
  await page.keyboard.press('o')
  await draw(page, [800, 300], [950, 420])
  await page.keyboard.press('l')
  await draw(page, [1000, 300], [1100, 420])
  await expect(elements(page)).toHaveCount(5)

  await page.keyboard.press('e')
  await page.mouse.click(600, 320)
  await expect(elements(page)).toHaveCount(4)
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await page.getByRole('button', { name: 'Keep drawing' }).click()
  await expect(elements(page)).toHaveCount(4)
  await page.getByRole('button', { name: 'Clear board', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Clear board', exact: true }).click()
  await expect(elements(page)).toHaveCount(0)
  expect(errors).toEqual([])
})

test('pan and zoom preserve drawing position; reset restores the viewport', async ({ page }) => {
  await page.goto('/')
  await draw(page, [400, 300], [500, 400])
  const stroke = elements(page).first()
  const original = await stroke.boundingBox()
  await page.keyboard.down('Space')
  await draw(page, [600, 500], [700, 540])
  await page.keyboard.up('Space')
  const panned = await stroke.boundingBox()
  expect(panned!.x).toBeCloseTo(original!.x + 100)
  expect(panned!.y).toBeCloseTo(original!.y + 40)
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(page.getByText('120%', { exact: true })).toBeVisible()
  expect((await stroke.boundingBox())!.width).toBeCloseTo(original!.width * 1.2)
  await page.getByRole('button', { name: 'Reset view' }).click()
  expect(await stroke.boundingBox()).toEqual(original)

  // Zoom around the cursor, then draw precisely in that transformed viewport.
  await page.mouse.move(650, 450)
  await page.keyboard.down('Control')
  await page.mouse.wheel(0, -60)
  await page.keyboard.up('Control')
  await expect(page.getByTestId('drawing-elements')).not.toHaveAttribute('transform', 'translate(0 0) scale(1)')
  await page.mouse.click(650, 450)
  const dot = await elements(page).nth(1).boundingBox()
  expect(dot!.x + dot!.width / 2).toBeCloseTo(650)
  expect(dot!.y + dot!.height / 2).toBeCloseTo(450)
})

test('escape cancels a draft, help works, and refresh discards drawing', async ({ page, context }) => {
  await page.goto('/')
  await page.mouse.move(400, 300)
  await page.mouse.down()
  await page.mouse.move(500, 400)
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect(elements(page)).toHaveCount(0)
  await draw(page, [400, 300], [500, 400])
  await page.getByRole('button', { name: 'Help and keyboard shortcuts' }).click()
  await expect(page.getByRole('dialog', { name: 'A few handy shortcuts' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  const otherTab = await context.newPage()
  await otherTab.goto('/')
  await expect(elements(otherTab)).toHaveCount(0)
  await otherTab.close()
  await page.reload()
  await expect(elements(page)).toHaveCount(0)
})

test('mobile layout and real touch drawing/pinch gestures', async ({ browser }, testInfo) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  const page = await context.newPage()
  await page.goto('http://127.0.0.1:5173/')
  await page.screenshot({ path: testInfo.outputPath('mobile.png') })
  await expect(page.getByRole('button', { name: 'Pen (P)', exact: true })).toBeVisible()
  const toolbar = await page.getByRole('toolbar').boundingBox()
  expect(toolbar!.x).toBeGreaterThanOrEqual(0)
  expect(toolbar!.x + toolbar!.width).toBeLessThanOrEqual(390)
  const style = await page.getByRole('complementary', { name: 'Stroke style' }).boundingBox()
  expect(style!.x).toBeGreaterThanOrEqual(0)
  expect(style!.x + style!.width).toBeLessThanOrEqual(390)

  const cdp = await context.newCDPSession(page)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 100, y: 300 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 200, y: 400 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(elements(page)).toHaveCount(1)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ id: 0, x: 140, y: 500 }, { id: 1, x: 240, y: 500 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ id: 0, x: 90, y: 500 }, { id: 1, x: 290, y: 500 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(elements(page)).toHaveCount(1)
  await expect(page.getByText('200%', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Reset view' }).tap()
  await expect(page.getByText('100%', { exact: true })).toBeVisible()
  // A two-finger gesture in eraser mode must not erase at touch-start.
  await page.getByRole('button', { name: 'Eraser (E)', exact: true }).tap()
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ id: 0, x: 150, y: 350 }, { id: 1, x: 250, y: 350 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(elements(page)).toHaveCount(1)
  await page.touchscreen.tap(150, 350)
  await expect(elements(page)).toHaveCount(0)
  await context.close()
})
